### ISSUE TITLE
Core Team

### ISSUE THREAD

**Issue by ashfurrow** [Moya/contributors#14]
Since [stepping back from the project](https://ashfurrow.com/blog/stepping-back-from-moya/), I've heard from contributors that they would like to see a Moya Core Team established to distinguish the leaders in the community. There are some great reasons, a few of them are:

- Reward contributors by distinguishing them
- Help retain existing contributors
- Imbue the Core Team with a sense of stewardship and responsibility
- Contextualize discussions for newcomers

So there are two steps that need to be taken, in no particular order:

1. We need to identify who would the initial Core Team be made up of.
2. We need a definition of what the Core Team is, does, and a defined process of adding new members.

I'm hoping to discuss the second point in this issue before submitting a PR. As for the initial Core Team, I think the following list is a good start:

- @sunshinejr
- @BasThomas
- @scottrhoyt
- @petester42
- @pedrovereza
- @AndrewSB
- @Dschee
- @colinta
- @SD10

If I'm missing someone, please let me know. 

**Important**: If you would *not* like to be added to the Core Team, that's okay! Just let me know. Timeframe on this is at least a week, so no rush. 

You can contact me in this issue's comments or privately at ash@ashfurrow.com . /cc @Moya/contributors

**Comment by sunshinejr** [comment]
@ashfurrow thank you for this one! For now I just wanted to add @pedrovereza to the list as he is missing.

**Comment by ashfurrow** [comment]
Ah! How could I forget! Will add.

**Comment by BasThomas** [comment]
Depending on definition of the CT, I'm not sure if I should be (stay?) a part, as I have severely less time now.

**Comment by SD10** [comment]
It's an honor to be part of this list :sob: Thank you

**Comment by ashfurrow** [comment]
Okay, thank you very much everyone! You're what has made the Moya project a success, and I'm grateful to all the hard work you've put in.
