### ISSUE TITLE
Section of contributing is still with template info

### ISSUE THREAD

**Issue by LucianoPAlmeida** [Moya/contributors#22]
Hey guys :))
I think the section below is with the template info 
[What about if you have problems that cannot be discussed in a public issue?](https://github.com/Moya/contributors/blob/master/Contributing.md#what-about-if-you-have-problems-that-cannot-be-discussed-in-a-public-issue)

**Comment by ashfurrow** [comment]
Hi there! The contributing guidelines for the Moya project itself can be found in the github.com/Moya/Moya repository, here: https://github.com/Moya/Moya/blob/master/Contributing.md#what-about-if-you-have-problems-that-cannot-be-discussed-in-a-public-issue What you have linked to _is_ indeed a template, one that we provide for other projects to adopt. 

Let me know what I can clarify.

**Comment by LucianoPAlmeida** [comment]
@ashfurrow Ahh I see, sorry
My mistake :))
