### ISSUE TITLE
Release Automation

### ISSUE THREAD

**Issue by ashfurrow** [Moya/contributors#5]
There are enough libraries I touch (Moya, [this](https://github.com/RxSwiftCommunity/NSObject-Rx/issues/8), and [this](https://github.com/ashfurrow/Action/issues/14)) that all need similar releases. 

It'd be _fab_ if I could abstract [Moya's current release script](https://github.com/Moya/Moya/blob/e069bc22e28b2d69cfcfbbae3cb15304d112fbd6/Rakefile#L27-L57) so this was a lot easier.

**Comment by mpurland** [comment]
Any luck with adding github release?

**Comment by ashfurrow** [comment]
TBH I've not had a chance to try it out yet. From your description, though, it looks like it should work!

**Comment by ashfurrow** [comment]
Took a look, seems a bit clumsy to use, but I'm going to give it a shot.

**Comment by ashfurrow** [comment]
So I looked into this, and Fastlane seems like the obvious answer. However, after reconstruct the existing Makefile tasks, we only save six lines of code. That's not significant enough to justify another dependency imo. 

The current Rakefile is 101 lines, uses Ruby in a clever-but-obvious way, and invokes command line tools that we're already familiar with. Using the current Rakefile would be a good solution, but we still need to duplicate it in each library. That's _probably_ not a huge deal. 

So yeah, I'm thinking maybe just create a gist that contains a sort of 'template', and then link to that gist in all the Rakefiles to make it easy for other developers to reuse. Anyone else opposed?

**Comment by orta** [comment]
Probably better off making a library releasing gem at this point

**Comment by ashfurrow** [comment]
Yeah it's worth considering, especially if we're moving towards a common-ish way of doing things.

**Comment by orta** [comment]
Could be done here: https://github.com/CocoaPods/cocoapods-plugins/issues/52

**Comment by segiddins** [comment]
This was done via https://github.com/Moya/Moya/pull/456, right?

**Comment by ashfurrow** [comment]
@segiddins I believe so, thanks!
