### ISSUE TITLE
Proposal: Convert to "Community Continuity"

### ISSUE THREAD

**Issue by orta** [Moya/contributors#6]
I feel like this name is closer to what we're getting at. This came out of a need for me + Ash to figure out how Moya should work properly, and to document this in a formalized way. 

The Moya Guidelines doc is a great example of how we think people should run projects. I want to make it easier to say you conform to this. There are three examples right now of conformity:
- Moya - it wrote, and owns the doc
- [Danger](http://github.com/danger/danger) - I added this to the README:
  
  > ## License, Contributor's Guidelines and Code of Conduct
  > 
  > This project is open source under the MIT license, which means you have full access to the source code and can modify it to fit your own needs.
  > 
  > This project subscribes to the [Moya Contributors Guidelines](https://github.com/Moya/contributors) which TLDR: means we give out push access easily and often.
  > 
  > Contributors subscribe to the [Contributor Code of Conduct](http://contributor-covenant.org/version/1/3/0/) based on the [Contributor Covenant](http://contributor-covenant.org) version 1.3.0.
- [Zewo](http://github.com/zewo/zewo) - who base their copy of their [CONTRIBUTING.md](https://github.com/Zewo/Zewo/blob/508703ca601be1f88d251d005059914f9de36985/CONTRIBUTING.md) from Moya's directly taking bits, and amending them for their own reasons.

Zewo's usage highlights a few flaws that I want to address:
- Background is specific to a project
- Names are obvious mine/Ash's
- There's specific bits around deployment
- Specifics around teams

I want to convert the Moya doc, into something that Danger/Zewo/Moya can all naturally conform to, and call that the "Community Continuity Doc." It'll never be as ubiquitous as a CoC, but I think it's a great pattern we should make easy to adopt. 

---

Separate to this, I think it might need to go into a new org eventually , and I think that this org should also make something like https://github.com/benbalter/squad_goals that automates the process of adding new people when their PRs have been merged. You could invite a specific GitHub account to your org, and it would handle the sending of the request, and maybe an email with a link to the CCD for that project. 

Dragging in @afeld who is a friend in the space, and might have ideas

**Comment by orta** [comment]
https://gnu.org/philosophy/why-free.html

**Comment by ashfurrow** [comment]
Following up on this, I _really_ like the name "Community Continuity", if you have any action items I can tackle, let me know 👍

**Comment by orta** [comment]
This is now [pretty high](https://github.com/orta/life/issues/63) on my [personal TODO](https://github.com/orta/life/issues), but the rough gist for actionable stuff is:
- Rewrite into a form that is applicable to every case, where you only sign with an email ( ala CoC/ LICENSE)
- Think about ways in which there could be an easy space for people to write their intentions for _why_
- Offer some example github auto-replies for maintainers e.g.

```
also, I've invited you to the org, as a part of [Moya Community Continuity](https://github.com/Moya/contributors/issues/6) - you're welcome to participate in PRs and help out at a level that works for you.
```

**Comment by ashfurrow** [comment]
Working on my talk for MCE tomorrow, came up with the term "community-driven development". I think there's more there, will explore and come back.
